<template>
    <div class="layout">
        <Header :header="headerObj[pageName]" />
        <router-view />
        <Footer />

        <LeftNav />
    </div>
</template>
<script setup>
import { reactive, toRefs, watchEffect, computed } from 'vue'
import { useRoute } from 'vue-router'

import Header from '@/components/header.vue'
import Footer from '@/components/footer.vue'
import LeftNav from '@/components/leftNav.vue'
// import headerConf from '@/utils/header'

import { useI18n } from 'vue-i18n'
const { t, locale } = useI18n()
const route = useRoute()
const headerObj = computed(() => {
    let header = {
        home: {
            leftIcon: "hleftIcon",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: "",
            rightIcon: "hRightIcon",
            isShowRightMoney: true,
            bgColor: "#202020",
        },
        match: {
            leftIcon: "boldCter",
            leftIconWidth: "58px",
            leftIconHeight: "19px",
            center: "",
            rightIcon: "hRightIcon",
            isShowRightMoney: true,
            bgColor: "#202020",
        },
        order: {
            leftIcon: "boldCter",
            leftIconWidth: "58px",
            leftIconHeight: "19px",
            center: "",
            rightIcon: "hRightIcon",
            isShowRightMoney: true,
            bgColor: "#202020",
        },
        tradingOrder: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t("safe.trading.order.title"),
            rightIcon: "",
            isShowRightMoney: false,
            bgColor: "#000",
        },
        safe: {
            leftIcon: "hleftIcon",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t("safe.title"),
            rightIcon: "hRightSafe",
            rightIconWidth: "18px",
            rightIconHeight: "18px",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        send: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t("send.title"),
            rightIcon: "hRightSafe",
            rightIconWidth: "18px",
            rightIconHeight: "18px",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        transfer: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t("transfer.title"),
            rightIcon: "hRightSafe",
            rightIconWidth: "18px",
            rightIconHeight: "18px",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        recharge: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t("recharge.title"),
            rightIcon: "hRightSafe",
            rightIconWidth: "18px",
            rightIconHeight: "18px",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        frecharge: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t("recharge.title"),
            rightIcon: "hRightSafe",
            rightIconWidth: "18px",
            rightIconHeight: "18px",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        withdraw: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t('withdraw.page.title.text'),
            rightIcon: "hRightSafe",
            rightIconWidth: "18px",
            rightIconHeight: "18px",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        addWalletAddress: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t('withdraw.add.newWallet.text'),
            rightIcon: "",
            rightIconWidth: "18px",
            rightIconHeight: "18px",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        addBankCard: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t('addBankCard.title.text'),
            rightIcon: "",
            rightIconWidth: "18px",
            rightIconHeight: "18px",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        editBankCard: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t('backapi.self.edit.bankcard'),
            rightIcon: "",
            rightIconWidth: "18px",
            rightIconHeight: "18px",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        addWallet: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t('withdraw.add.eWallet.text'),
            rightIcon: "",
            rightIconWidth: "18px",
            rightIconHeight: "18px",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        swapInfo: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t('swapInfo.page.title'),
            rightIcon: "",
            rightIconWidth: "",
            rightIconHeight: "",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        result: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t('fuc.match.records'),
            rightIcon: "",
            rightIconWidth: "",
            rightIconHeight: "",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        rebateReport: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t('fuc.rebate.center'),
            rightIcon: "",
            rightIconWidth: "",
            rightIconHeight: "",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        personalInfomation: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t('leftNav.personalInformation.text'),
            rightIcon: "",
            rightIconWidth: "",
            rightIconHeight: "",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        loginPwdSet: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t('personal.menu.password'),
            rightIcon: "",
            rightIconWidth: "",
            rightIconHeight: "",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        withdrawPwdSet: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t('personal.menu.withdrawpwd'),
            rightIcon: "",
            rightIconWidth: "",
            rightIconHeight: "",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        updatePhone: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t('security.phone.text'),
            rightIcon: "",
            rightIconWidth: "",
            rightIconHeight: "",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        updateEmail: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t('security.mail.text'),
            rightIcon: "",
            rightIconWidth: "",
            rightIconHeight: "",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        bindPhone: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t('security.bind.phone.text'),
            rightIcon: "",
            rightIconWidth: "",
            rightIconHeight: "",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        bindEmail: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t('security.bind.mail.text'),
            rightIcon: "",
            rightIconWidth: "",
            rightIconHeight: "",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        cardManage: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t('leftNav.cardManagement.text'),
            rightIcon: "",
            rightIconWidth: "",
            rightIconHeight: "",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        fundsRecords: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t('fundsRecords.title.text'),
            rightIcon: "",
            rightIconWidth: "",
            rightIconHeight: "",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        invite: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t('leftNav.invite.text'),
            rightIcon: "",
            rightIconWidth: "",
            rightIconHeight: "",
            isShowRightMoney: false,
            bgColor: "",
        },
        download: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t('fuc.app.download'),
            rightIcon: "",
            rightIconWidth: "",
            rightIconHeight: "",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        about: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t('leftNav.aboutCTER.ONLINE.text'),
            rightIcon: "",
            rightIconWidth: "",
            rightIconHeight: "",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        purchaseAmount: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: "",
            rightIcon: "",
            rightIconWidth: "",
            rightIconHeight: "",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        confirmBuy: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: "",
            rightIcon: "",
            rightIconWidth: "",
            rightIconHeight: "",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        successfulArrival: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: "",
            rightIcon: "",
            rightIconWidth: "",
            rightIconHeight: "",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        cancelOrder: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: "",
            rightIcon: "",
            rightIconWidth: "",
            rightIconHeight: "",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        orderStatus: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: "",
            rightIcon: "",
            rightIconWidth: "",
            rightIconHeight: "",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        buy: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: "",
            rightIcon: "",
            rightIconWidth: "",
            rightIconHeight: "",
            isShowRightMoney: false,
            bgColor: "#0b0b0b",
        },
        betPage: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t("betPage.title"),
            rightIcon: "bell",
            noticeLink: "/sysNotice",
            isShowRightMoney: false,
            bgColor: "transparent",
            link: "/contest",
        },
        sysNotice: {
            leftIcon: "back",
            leftIconWidth: "32px",
            leftIconHeight: "32px",
            center: t("sysNotice.title"),
            rightIcon: "",
            isShowRightMoney: false,
            bgColor: "#202020",
            link: "/home",
        },
        partner: {
            leftIcon: "cter",
            leftIconWidth: "58px",
            leftIconHeight: "19px",
            center: "",
            rightIcon: "bell",
            isShowRightMoney: true,
            bgColor: "#202020",
        },
    }
    return header
})
const state = reactive({
    pageName: route.name,

})
watchEffect(() => {
    // console.log(route.name);
    state.pageName = route.name

})
const { pageName } = toRefs(state)
</script>
<style scoped lang='scss'>
.layout {
    padding-top: 44px;
    padding-bottom: 50px;
    height: 100%;
    box-sizing: border-box;
}
</style>