const headerConf = {
  home: {
    leftIcon: "hleftIcon",
    leftIconWidth: "32px",
    leftIconHeight: "32px",
    center: "",
    rightIcon: "hRightIcon",
    isShowRightMoney: true,
    bgColor: "#202020",
  },
  match: {
    leftIcon: "boldCter",
    leftIconWidth: "58px",
    leftIconHeight: "19px",
    center: "",
    rightIcon: "hRightIcon",
    isShowRightMoney: true,
    bgColor: "#202020",
  },
  order: {
    leftIcon: "boldCter",
    leftIconWidth: "58px",
    leftIconHeight: "19px",
    center: "",
    rightIcon: "hRightIcon",
    isShowRightMoney: true,
    bgColor: "#202020",
  },
  safe: {
    leftIcon: "hleftIcon",
    leftIconWidth: "32px",
    leftIconHeight: "32px",
    center: "Safebox",
    rightIcon: "hRightSafe",
    rightIconWidth: "18px",
    rightIconHeight: "18px",
    isShowRightMoney: false,
    bgColor: "#0b0b0b",
  },
  send: {
    leftIcon: "back",
    leftIconWidth: "32px",
    leftIconHeight: "32px",
    center: "Send",
    rightIcon: "hRightSafe",
    rightIconWidth: "18px",
    rightIconHeight: "18px",
    isShowRightMoney: false,
    bgColor: "#0b0b0b",
  },
  transfer: {
    leftIcon: "back",
    leftIconWidth: "32px",
    leftIconHeight: "32px",
    center: "Transfer",
    rightIcon: "hRightSafe",
    rightIconWidth: "18px",
    rightIconHeight: "18px",
    isShowRightMoney: false,
    bgColor: "#0b0b0b",
  },
  recharge: {
    leftIcon: "back",
    leftIconWidth: "32px",
    leftIconHeight: "32px",
    center: "Recharge",
    rightIcon: "hRightSafe",
    rightIconWidth: "18px",
    rightIconHeight: "18px",
    isShowRightMoney: false,
    bgColor: "#0b0b0b",
  },
  swapInfo: {
    leftIcon: "back",
    leftIconWidth: "32px",
    leftIconHeight: "32px",
    center: "Confirm Swap Info",
    rightIcon: "",
    rightIconWidth: "",
    rightIconHeight: "",
    isShowRightMoney: false,
    bgColor: "#0b0b0b",
  },
  purchaseAmount: {
    leftIcon: "back",
    leftIconWidth: "32px",
    leftIconHeight: "32px",
    center: "",
    rightIcon: "",
    rightIconWidth: "",
    rightIconHeight: "",
    isShowRightMoney: false,
    bgColor: "#0b0b0b",
  },
  buy: {
    leftIcon: "back",
    leftIconWidth: "32px",
    leftIconHeight: "32px",
    center: "",
    rightIcon: "",
    rightIconWidth: "",
    rightIconHeight: "",
    isShowRightMoney: false,
    bgColor: "#0b0b0b",
  },
  betPage: {
    leftIcon: "back",
    leftIconWidth: "32px",
    leftIconHeight: "32px",
    center: "Friendlies Clubs",
    rightIcon: "bell",
    noticeLink: "/sysNotice",
    isShowRightMoney: false,
    bgColor: "transparent",
    link: "/contest",
  },
  sysNotice: {
    leftIcon: "back",
    leftIconWidth: "32px",
    leftIconHeight: "32px",
    center: "Message Center",
    rightIcon: "",
    isShowRightMoney: false,
    bgColor: "#202020",
    link: "/home",
  },
  partner: {
    leftIcon: "cter",
    leftIconWidth: "58px",
    leftIconHeight: "19px",
    center: "",
    rightIcon: "bell",
    isShowRightMoney: true,
    bgColor: "#202020",
  },
};
export default headerConf;
